### ISSUE TITLE
Endpoint for Events for the new API

### ISSUE THREAD

**Issue by angelolz1** [Nookipedia/nookipedia-api#10]
Hello, I would like to see an endpoint for the events that occur in AC:NH in the new API. I am not sure if it is planned or not, but would love to know if it is in the to-do list!

As well as making a new AC:NH events endpoint for the new API, I would like to request if it is possible for invalid dates to return an invalid date error. For example on the old API, giving a [date of September 31st](https://nookipedia.com/api/today/20200931) would return the events on October 1. Giving an invalid date (like [March 32nd](https://nookipedia.com/api/today/20200332)) would return December 31st on a Wednesday. 

Another request for the endpoint on the new API would be the ability to look up all the events that happen on a certain month, which would allow us to see seasonal events as well as villager birthdays that are happening during the month given.

**Comment by janreggie** [comment]
Adding to the discussion, some potential ideas for this API:

* Query parameters
  * `month`: similar format to ones that are already provided `01`, `1`, `"jan"`, `"january"`
  * `day`: integer, `01` to `31`
  * `year`: integer, `2000` to `2050`, or until when is desired
    * Treat invalid `month`, `day`, and `year` combinations as illegal, which [is easily doable](https://stackoverflow.com/a/9987935/14020202)
  * `game`: accept only one from `"DNM"` `"AC"`, `"E_PLUS"`, `"WW"`, `"CF"`, `"NL"`, or `"NH"`
  * `hemisphere`: optional param, defaults to `"north"`, useful for NH data where the Bug-Off is dependent on
* Returns
  * `birthday`: an array of objects detailing whose birthday it is
  * `events`: an array of objects detailing the events on that particular day

`birthday` is already implemented similarly in `/villagers`, but `events`, such as New Year's, the Bug-Off, etc. have yet to be stored in any [Cargo table](https://nookipedia.com/wiki/Special:CargoTables), and storing them may be another question. There are events that fall on specific dates e.g., New Year's, on a specific weekday e.g., the Fishing Tourneys, or using a lookup table e.g., Festivale....

**Comment by Micalobia** [comment]
Honestly, the biggest thing that needs to happen for this is a cargo table to exist for events.
