### ISSUE TITLE
.gitignore, venv, and requirements.txt to facilitate ease of development and deployment

### ISSUE THREAD

**Issue by janreggie** [Nookipedia/nookipedia-api#11]
This repository does not use a .gitignore to ensure that changes to `config.ini` and `dashboard-config.cfg`. While doing so may make necessary changes to these files [require a force flag on `git-add`](https://stackoverflow.com/questions/8006393/force-add-despite-the-gitignore-file), this will provide benefit to those working on the project who just `git add -A` everything.

In addition, as a Python project, the use of a virtual environment is vital. For future users and developers, a virtual environment can be used in order for the rest of the system to be unaffected as well as to ensure that dependencies are met by simply doing a `pip install -r requirements.txt`. 

Changes to the way the project is deployed will also mean changes in the README. I will be submitting a corresponding pull request in a while.

**Comment by KevinPayravi** [comment]
This all sounds good, thank you!
