### ISSUE TITLE
Today endpoint

### ISSUE THREAD

**Issue by KevinPayravi** [Nookipedia/nookipedia-api#2]
A "today" endpoint that returns the day's events. These would include villager birthdays as well as in-game activities across all games.

**Comment by nguyen-anthony** [comment]
`https://api.nookipedia.com/nh/events?date=today`

This is already implemented

```
[
	{
		"event": "Maelle's birthday",
		"date": "2022-04-08",
		"type": "Birthday",
		"url": "https://nookipedia.com/wiki/Maelle"
	}
]
```
