### ISSUE TITLE
API Experienced fatal error

### ISSUE THREAD

**Issue by Micalobia** [Nookipedia/nookipedia-api#40]
When using the `fish` or `bugs` endpoint (maybe others, I didn't check too closely), it returns an error when `excludedetails=true` and `month` are set at the same time.

**Comment by KevinPayravi** [comment]
Thanks for reporting this! Do you know if this used to work, or is this the first time you've tried?

**Comment by Micalobia** [comment]
This is the first time I've tried using 1.3.0, noticed it when rewriting my Discord bot that's still using 1.1.0

**Comment by KevinPayravi** [comment]
There was a key error, resolved with https://github.com/Nookipedia/nookipedia-api/commit/9f8140b92ea5ee94cafd32b4006de3ae2993dea9

Thanks again for reporting!
