### ISSUE TITLE
Create Gyroids endpoints

### ISSUE THREAD

**Issue by KevinPayravi** [Nookipedia/nookipedia-api#68]
ACNH Gyroids are considered a new type of item and need their own endpoint.

Cargo tables:
https://nookipedia.com/wiki/Special:CargoTables/nh_gyroid
https://nookipedia.com/wiki/Special:CargoTables/nh_gyroid_variation

**Comment by PanchamBro** [comment]
Curious how do you create a new endpoint?

**Comment by KevinPayravi** [comment]
Resolved by #91, now live
